station_name = {
  # Island Line
  "Kennedy Town",
  "HKU",
  "Sai Ying Pun",
  "Sheung Wan",
  "Central",
  "Admiralty",
  "Wan Chai",
  "Causeway Bay",
  "Tin Hau",
  "Fortress Hill",
  "North Point",
  "Quarry Bay",
  "Tai Koo",
  "Sai Wan Ho",
  "Shau Kei Wan",
  "Heng Fa Chuen",
  "Chai Wan",

  # Tseung Kwan O Line
  "Po Lam",
  "Hang Hau",
  "TKO",
  "LOHAS Park",
  "TKL",
  "Yau Tong",
  # "Quarry Bay",
  # "North Point",

  # Kwun Tong Line
  "Whampoa",
  "Ho Man Tin",
  "Yau Ma Tei",
  "Mong Kok",
  "Prince Edward",
  "Shek Kip Mei",
  "Kowloon Tong",
  "Lok Fu",
  "Wong Tai Sin",
  "Diamond Hill",
  "Choi Hung",
  "Kowloon Bay",
  "Ngau Tau Kok",
  "KT",
  "Lam Tin",
  # "Yau Tong",
  # "TKL",

  # Tsuen Wan Line
  # "Central",
  # "Admiralty",
  "Tsim Sha Tsui",
  "Jordan",
  # "Yau Ma Tei",
  # "Mong Kok",
  # "Prince Edward",
  "Sham Shui Po",
  "Cheung Sha Wan",
  "Lai Chi Kok",
  "Mei Foo",
  "Lai King",
  "Kwai Fong",
  "Kwai Hing",
  "Tai Wo Hau",
  "Tsuen Wan",

  # East Rail Line
  # Admiralty
  "Exhibition Centre",
  "Hung Hom",
  "Mong Kok East",
  # "Kowloon Tong",
  "Tai Wai",
  "Sha Tin",
  "Fo Tan",
  "Racecourse", 
  "University",
  "Tai Po Market",
  "Tai Wo",
  "Fanling",
  "Sheung Shui",
  "Lo Wu",
  "Lok Ma Chau",

  # Tung Chung Line
  "Hong Kong",
  "Kowloon",
  "Olympic",
  "Nam Cheong",
  # "Lai King",
  "Tsing Yi",
  "Sunny Bay",
  "Tung Chung",

  # Disneyland Line
  "Sunny Bay",
  "Disneyland",

  # South Island Line
  "South Horizons",
  "Lei Tung",
  "Wong Chuk Hang",
  "Ocean Park",
  # "Admiralty",

  # Airport Express
  # "Hong Kong",
  # "Kowloon",
  "Tsing Yi",
  "Airport",
  "AsiaWorld-Expo",

  # Tuen Ma Line
  "Wu Kai Sha",
  "Ma On Shan",
  "Heng On",
  "Tai Shui Hang",
  "Shek Mun",
  "City One",
  "Sha Tin Wai",
  "Che Kung Temple",
  # "Tai Wai",
  "Hin Keng", 
  # "Diamond Hill",
  "Kai Tak",
  "Sung Wong Toi",
  "To Kwa Wan",
  "Ho Man Tin",
  "Hung Hom",
  "East Tsim Sha Tsui",
  "Austin",
  # "Nam Cheong",
  # "Mei Foo",
  "Tsuen Wan West",
  "Kam Sheung Road",
  "Yuen Long",
  "Long Ping",
  "Tin Shui Wai",
  "Siu Hong",
  "Tuen Mun"
}


stations_branches = {
  # Tseung Kwan O Line
  "Po Lam": ["Hang Hau"], 
  "Hang Hau": ["Po Lam", "TKO"],
  "TKO": ["Hang Hau", "LOHAS Park", "TKL"], 
  "LOHAS Park": ["TKO"],
  "TKL": ["TKO", "Yau Tong"], 
  "Yau Tong": ["TKL", "Lam Tin", "Quarry Bay"],
  
  # Island Line
  "Kennedy Town": ["HKU"], 
  "HKU": ["Kennedy Town", "Sai Ying Pun"],
  "Sai Ying Pun": ["HKU", "Sheung Wan"], 
  "Sheung Wan": ["Sai Ying Pun", "Central"],
  "Central": ["Sheung Wan", "Admiralty"], 
  "Admiralty": ["Central", "Tsim Sha Tsui", "Wan Chai", "Ocean Park"],
  "Wan Chai": ["Admiralty", "Causeway Bay"], 
  "Causeway Bay": ["Wan Chai", "Tin Hau"],
  "Tin Hau": ["Causeway Bay", "Fortress Hill"], 
  "Fortress Hill": ["Tin Hau", "North Point"],
  "North Point": ["Fortress Hill", "Quarry Bay"], 
  "Quarry Bay": ["North Point", "Tai Koo", "Yau Tong"],
  "Tai Koo": ["Quarry Bay", "Sai Wan Ho"], 
  "Sai Wan Ho": ["Tai Koo", "Shau Kei Wan"],
  "Shau Kei Wan": ["Sai Wan Ho", "Heng Fa Chuen"], 
  "Heng Fa Chuen": ["Shau Kei Wan", "Chai Wan"],
  "Chai Wan": ["Heng Fa Chuen"],

  # Kwun Tong Line
  "Lam Tin": ["Yau Tong", "KT"], 
  "KT": ["Lam Tin", "Ngau Tau Kok"],
  "Ngau Tau Kok": ["KT", "Kowloon Bay"], 
  "Kowloon Bay": ["Ngau Tau Kok", "Choi Hung"],
  "Choi Hung": ["Kowloon Bay", "Diamond Hill"], 
  "Diamond Hill": ["Choi Hung", "Wong Tai Sin", "Kai Tak", "Hin Keng"],
  "Wong Tai Sin": ["Diamond Hill", "Lok Fu"], 
  "Lok Fu": ["Wong Tai Sin", "Kowloon Tong"],
  "Kowloon Tong": ["Lok Fu", "Shek Kip Mei", "Tai Wai", "Mong Kok East"],
  "Shek Kip Mei": ["Kowloon Tong", "Prince Edward"], 
  "Prince Edward": ["Shek Kip Mei", "Mong Kok", "Sham Shui Po"],
  "Mong Kok": ["Prince Edward", "Yau Ma Tei"], 
  "Yau Ma Tei": ["Mong Kok", "Ho Man Tin", "Jordan"],
  "Ho Man Tin": ["Yau Ma Tei", "Whampoa", "To Kwa Wan", "Hung Hom"], 
  "Whampoa": ["Ho Man Tin"],

  # Tsuen Wan Line
  "Tsim Sha Tsui": ["Admiralty", "Jordan"], 
  "Jordan": ["Tsim Sha Tsui", "Yau Ma Tei"],
  "Sham Shui Po": ["Prince Edward", "Cheung Sha Wan"], 
  "Cheung Sha Wan": ["Sham Shui Po", "Lai Chi Kok"],
  "Lai Chi Kok": ["Cheung Sha Wan", "Mei Foo"],
  "Mei Foo": ["Lai Chi Kok", "Lai King", "Nam Cheong", "Tsuen Wan West"],
  "Lai King": ["Mei Foo", "Kwai Fong", "Tsing Yi", "Nam Cheong"],
  "Kwai Fong": ["Lai King", "Kwai Hing"],
  "Kwai Hing": ["Kwai Fong", "Tai Wo Hau"],
  "Tai Wo Hau": ["Kwai Hing", "Tsuen Wan"],
  "Tsuen Wan": ["Tai Wo Hau"],

  # East Rail Line
  "Exhibition Centre": ["Admiralty", "Hung Hom"], 
  "Hung Hom": ["Exhibition Centre", "Mong Kok East", "Ho Man Tin", "East Tsim Sha Tsui"],
  "Mong Kok East": ["Hung Hom", "Kowloon Tong"],
  "Tai Wai": ["Che Kung Temple", "Sha Tin", "Kowloon Tong", "Hin Keng"],
  "Sha Tin": ["Tai Wai", "Fo Tan"],
  "Fo Tan": ["Sha Tin", "University"],
  "Racecourse": ["Sha Tin", "University"],
  "University": ["Fo Tan", "Tai Po Market"],
  "Tai Po Market": ["University", "Tai Wo"],
  "Tai Wo": ["Tai Po Market", "Fanling"],
  "Fanling": ["Tai Wo", "Sheung Shui"],
  "Sheung Shui": ["Fanling", "Lo Wu", "Lok Ma Chau"],
  "Lo Wu": ["Sheung Shui"],
  "Lok Ma Chau": ["Sheung Shui"],

  # Tung Chung Line
  "Hong Kong": ["Kowloon"],
  "Kowloon": ["Hong Kong", "Olympic"],
  "Olympic": ["Kowloon", "Nam Cheong"],
  "Nam Cheong": ["Olympic", "Mei Foo", "Austin"],
  "Tsing Yi": ["Lai King", "Sunny Bay"],
  "Sunny Bay": ["Tsing Yi", "Tung Chung", "Disneyland"],
  "Tung Chung": ["Sunny Bay"],

  # Disneyland Resort Line
  "Disneyland": ["Sunny Bay"],

  # South Island Line
  "South Horizons": ["Lei Tung"],
  "Lei Tung": ["South Horizons", "Wong Chuk Hang"],
  "Wong Chuk Hang": ["Lei Tung", "Ocean Park"],
  "Ocean Park": ["Wong Chuk Hang", "Admiralty"],

  # Airport Express
  "Hong Kong": ["Kowloon"],
  "Kowloon": ["Hong Kong", "Tsing Yi"],
  "Tsing Yi": ["Kowloon", "Airport"],
  "Airport": ["Tsing Yi", "AsiaWorld-Expo"],
  "AsiaWorld-Expo": ["Airport"],

  # Tuen Ma Line
  "Wu Kai Sha": ["Ma On Shan"],
  "Ma On Shan": ["Wu Kai Sha", "Heng On"],
  "Heng On": ["Ma On Shan", "Tai Shui Hang"],
  "Tai Shui Hang": ["Heng On", "Shek Mun"],
  "Shek Mun": ["Tai Shui Hang", "City One"],
  "City One": ["Shek Mun", "Sha Tin Wai"],
  "Sha Tin Wai": ["City One", "Che Kung Temple"],
  "Che Kung Temple": ["Sha Tin Wai", "Tai Wai"],
  "Hin Keng": ["Tai Wai", "Diamond Hill"],
  "Kai Tak": ["Diamond Hill", "Sung Wong Toi"], 
  "Sung Wong Toi": ["Kai Tak", "To Kwa Wan"],
  "To Kwa Wan": ["Sung Wong Toi", "Ho Man Tin"],
  "East Tsim Sha Tsui": ["Hung Hom", "Austin"],
  "Austin": ["East Tsim Sha Tsui", "Nam Cheong"],
  "Tsuen Wan West": ["Mei Foo", "Kam Sheung Road"],
  "Kam Sheung Road": ["Tsuen Wan West", "Yuen Long"],
  "Yuen Long": ["Kam Sheung Road", "Long Ping"],
  "Long Ping": ["Yuen Long", "Tin Shui Wai"],
  "Tin Shui Wai": ["Long Ping", "Siu Hong"],
  "Siu Hong": ["Tin Shui Wai", "Tuen Mun"],
  "Tuen Mun": ["Siu Hong"],
}

stations_pos = {
  # Island Line (bottom row, west → east)
  "Kennedy Town": (100, 800),
  "HKU": (150, 800),
  "Sai Ying Pun": (200, 800),
  "Sheung Wan": (250, 800),
  "Central": (300, 800),
  "Admiralty": (350, 800),
  "Wan Chai": (400, 800),
  "Causeway Bay": (450, 800),
  "Tin Hau": (500, 800),
  "Fortress Hill": (550, 800),
  "North Point": (600, 800),
  "Quarry Bay": (650, 800),
  "Tai Koo": (700, 800),
  "Sai Wan Ho": (750, 800),
  "Shau Kei Wan": (800, 800),
  "Heng Fa Chuen": (850, 800),
  "Chai Wan": (900, 800),

  # Tseung Kwan O Line (branching northeast)
  "Po Lam": (1100, 500),
  "Hang Hau": (1050, 500),
  "TKO": (1000, 500),
  "LOHAS Park": (1050, 600),
  "TKL": (950, 500),
  "Yau Tong": (900, 500),

  # Kwun Tong Line (northbound from Yau Tong)
  "Lam Tin": (850, 500),
  "KT": (850, 450),
  "Ngau Tau Kok": (850, 400),
  "Kowloon Bay": (800, 400),
  "Choi Hung": (750, 400),
  "Diamond Hill": (700, 400),
  "Wong Tai Sin": (650, 400),
  "Lok Fu": (600, 400),
  "Kowloon Tong": (550, 400),
  "Shek Kip Mei": (500, 400),
  "Prince Edward": (450, 450),
  "Mong Kok": (450, 500),
  "Yau Ma Tei": (450, 550),
  "Ho Man Tin": (600, 600),
  "Whampoa": (650, 650),

  # Tsuen Wan Line (northbound from Central)
  "Tsim Sha Tsui": (450, 700),
  "Jordan": (450, 600),
  "Yau Ma Tei": (450, 550),
  "Mong Kok": (450, 500),
  "Prince Edward": (450, 450),
  "Sham Shui Po": (400, 400),
  "Cheung Sha Wan": (350, 400),
  "Lai Chi Kok": (300, 400),
  "Mei Foo": (250, 400),
  "Lai King": (200, 400),
  "Kwai Fong": (150, 400),
  "Kwai Hing": (100, 400),
  "Tai Wo Hau": (50, 400),
  "Tsuen Wan": (0, 400),

  # East Rail Line (northbound from Hung Hom)
  "Exhibition Centre": (450, 750), 
  "Hung Hom": (500, 650),
  "Mong Kok East": (600, 500),
  # "Kowloon Tong": (550, 400),
  "Tai Wai": (550, 250),
  "Sha Tin": (550, 200),
  "Fo Tan": (550, 150),
  "Racecourse": (650, 100), 
  "University": (500, 100),
  "Tai Po Market": (450, 100),
  "Tai Wo": (400, 100),
  "Fanling": (350, 100),
  "Sheung Shui": (300, 100),
  "Lo Wu": (250, 100),
  "Lok Ma Chau": (250, 150),

  # Tung Chung Line
  "Hong Kong": (300, 750),
  "Kowloon": (250, 650),
  "Olympic": (250, 575),
  "Nam Cheong": (250, 500),
  # "Lai King": (200, 400),
  "Tsing Yi": (150, 450),
  "Sunny Bay": (100, 600),
  "Tung Chung": (50, 700),

  # Disneyland Resort Line
  "Disneyland": (150, 650),

  # South Island Line
  "South Horizons": (200, 950),
  "Lei Tung": (250, 900),
  "Wong Chuk Hang": (300, 900),
  "Ocean Park": (350, 850),
  # "Admiralty": (350, 800),

  # Airport Express
  "Airport": (0, 650),
  "AsiaWorld-Expo": (0, 550),

  # Tuen Ma Line
  "Wu Kai Sha": (950, 100),
  "Ma On Shan": (900, 100),
  "Heng On": (850, 100),
  "Tai Shui Hang": (800, 100),
  "Shek Mun": (750, 100),
  "City One": (700, 100),
  "Sha Tin Wai": (650, 150),
  "Che Kung Temple": (650, 200),
  # "Tai Wai": (550, 250),
  "Hin Keng": (600, 300), 
  # "Diamond Hill": (700, 400),
  "Kai Tak": (700, 450),
  "Sung Wong Toi": (700, 500),
  "To Kwa Wan": (650, 550),
  # "Ho Man Tin": (550, 600),
  # "Hung Hom": (400, 600),
  "East Tsim Sha Tsui": (400, 650),
  "Austin": (400, 550),
  # "Nam Cheong": (200, 450),
  # "Mei Foo": (900, 150),
  "Tsuen Wan West": (0, 300),
  "Kam Sheung Road": (-50, 250),
  "Yuen Long": (-50, 200),
  "Long Ping": (-50, 150),
  "Tin Shui Wai": (-100, 100),
  "Siu Hong": (-150, 200),
  "Tuen Mun": (-150, 250),
}

station_opened = {name: True for name in station_name}

station_opened["Po Lam"] = True

